### ISSUE TITLE
Useless debounce

### ISSUE THREAD

**Issue by ARMATAV** [karl-run/react-bottom-scroll-listener#20] opened 2019-09-21 21:56 UTC
The debounce blocks the firing of the first event, making it completely useless for it's intended purpose.

**Comment by karl-run** [comment] 2019-09-24 05:48
I haven't observed the behaviour you are describing. Are you able to provide an reproduction example?

Also, have you tried setting `debounce={0}`? It literally disables the debounce completely.

**Comment by iwikal** [comment] 2020-01-08 15:56
This is probably a duplicate of #13

**Comment by karl-run** [comment] 2020-01-09 15:05
Good point iwikal. :) Closing as duplicate of #13

**Closed by karl-run** 2020-01-09 15:05 UTC
